version: '3.9'
services:
  db:
    image: mysql:8.0.33
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_USER_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_mktech
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - mktech-network
  rest-with-mktech:
    image: mtalesilv/rest-api-complete
    restart: always
    build: ./rest-api-complete
    working_dir: /rest-api-complete
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_mktech?usetimezone=true&servertimezone=utc
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - mktech-network
networks:
  mktech-network:
    driver: bridge
